### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by dddeveloperrr** [alireza6677/JeyBoard#1]
سلام.
دوست عزیز یه چندتا لینک اسکرین شات هم از برنامت بزار توی توضیحات پروژه. مرسی

**Comment by TheWeirdDev** [comment]
سلام. ممنون از اینکه اشاره کردین . اضافه می کنم

**Comment by farooqkz** [comment]
اضافه شده پس بنظرم بهتره این بسته بشه.
